### ISSUE TITLE
Wybór technologi gui

### ISSUE THREAD

**Issue by QcKucyk** [dud1666/iscom#2]
Wybór technologi gui

**Comment by pduda98** [comment]
**Moje propozycje:**

  **1. Windows Form**
Technologia powiązana z Visual Studio, umożliwia tworzenie aplikacji okienkowych. Chyba najpopularniejsza dla C#. Można znaleźć mnóstwo oficjalnych i nieoficjalnych poradników. Jako, że już wszyscy mieliśmy styczność z VS to może to być dla nas najwygodniejsza opcja.

**2. Aplikacja internetowa**
Korzystając z Visual Studio jesteśmy w stanie także stworzyć witrynę internetową w technologii .NET. Poradników na internecie jest niemało, więc też bylibyśmy w stanie sobie poradzić.

PS: Postaram się poszukać trochę więcej propozycji, ponieważ po wpisaniu w google "C# GUI" pojawiają się praktycznie same informacje na temat Windows Form.

**Comment by dud1666** [comment]
wybrano!! jest progres

**Comment by pduda98** [comment]
wybrano!! jest progres

**Comment by pduda98** [comment]
wybrano!! jest progres
