### ISSUE TITLE
Wybór architektury aplikacji w języku C#

### ISSUE THREAD

**Issue by QcKucyk** [dud1666/iscom#3]
Wybór architektury aplikacji w języku C#

**Comment by Scaaz** [comment]
Proponuję **aplikację monolityczną** - całkowicie niezależna w warunkach działania. 
Cała logika aplikacji jest zawarta w pojedynczym projekcie, skompilowana do jednego zestawu i wdrożona jako pojedyncza jednostka. Wadą jest rozmiar i złożoność projektu.(coraz więcej plików i folderów)

Możliwe, że bardziej czytelnie będzie z architekturą **N-Layer** w której dzielimy logikę aplikacji do warstw (np. na trzy: User Interface, Business Logic, Data acces) .Warstwa interfejsu użytkownika nie powinna bezpośrednio wykonywać żadnych żądań do Data acces. Tutaj problemem jest, że warstwa interfejsu zależy od logiki, która zależy od data acces w wyniku czego testowanie logiki biznesowej będzie trudne i będzie wymagało testowej bazy danych. Warto wspomnieć że skalowność jest bardzo dobra. Aplikację będzie można znacznie rozbudować o dodatkowe możliwości
https://docs.microsoft.com/pl-pl/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures

**Comment by Scaaz** [comment]
Wszystko pakujemy do jednego
